# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_app', models.CharField(blank=True, max_length=30, null=True)),
                ('amigos', models.ManyToManyField(blank=True, related_name='_usuario_amigos_+', to=settings.AUTH_USER_MODEL)),
                ('propiedades_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_usuario+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
