# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_grupal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_grupal',
            name='creador_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota_grupal',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
    ]
